# Generated by Django 5.1.3 on 2024-12-03 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_transaction_history_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_history',
        ),
    ]
