# Generated by Django 5.1.3 on 2024-12-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_transaction_transaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_history',
            field=models.ManyToManyField(related_name='transactions', to='user.transaction_history'),
        ),
    ]
