# Generated by Django 5.1.3 on 2024-12-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(default='sapareloaded', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='default_image.jpg', upload_to='profiles/'),
        ),
    ]
