# Generated by Django 5.1.3 on 2024-12-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_account_full_name_alter_account_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_history',
        ),
        migrations.DeleteModel(
            name='Transaction_history',
        ),
    ]
